<?php

function pt_parallax_theme($existing, $type, $theme, $path) {
	$items = array (
		'page__storypage' => array (
		'variables' => array(),
		'template' => 'page--storypage' ,
		'base hook' => 'page',
		'path' => drupal_get_path('module', 'pt_parallax').'/templates',
		),
	);
	$items['dividerslide'] = array(
	'template' => 'dividerslide',
	'path' => drupal_get_path('module', 'pt_parallax') . '/templates',
	);
	$items['leftslide'] = array(
	'template' => 'leftslide',
	'path' => drupal_get_path('module', 'pt_parallax') . '/templates',
	);
	$items['rightslide'] = array(
	'template' => 'rightslide',
	'path' => drupal_get_path('module', 'pt_parallax') . '/templates',
	);
	$items['permanentslide'] = array(
	'template' => 'permanentslide',
	'path' => drupal_get_path('module', 'pt_parallax') . '/templates',
	);
  return $items;
}

 /*
 *
 * Implements hook_preprocess_page
 *
 */

function pt_parallax_preprocess_page(&$vars, $hook){
    global $user, $is_mobile;
    
    if (isset($vars['node'])) {
      if ($vars['node']->type == 'storypage' && arg(2) != 'edit'){
      	$vars['theme_hook_suggestions'][] = 'page__storypage'; 
     //  	drupal_add_js(drupal_get_path('module', 'pt_parallax'). '/scripts/jquery.localscroll-1.2.7-min.js');
    	drupal_add_js(drupal_get_path('module', 'pt_parallax'). '/scripts/jquery.parallax-1.1.3.js');
    	drupal_add_js(drupal_get_path('module', 'pt_parallax'). '/scripts/jquery.parallax.min.js');
    	drupal_add_js(drupal_get_path('module', 'pt_parallax'). '/scripts/parallax.js');
    	drupal_add_js(drupal_get_path('module', 'pt_parallax'). '/scripts/modernizr.js');
    	// drupal_add_js(drupal_get_path('module', 'pt_parallax'). '/scripts/scrollTo.js');
    	drupal_add_css(drupal_get_path('module', 'pt_parallax'). '/css/parallax_style.css');
    	// css/parallax_style.css
      }   
    }
}
    /*
 * Implements hook_theme_registry_alter.  
 * This hook will be used to reference our custom template pages. 
 *
 */
function pt_parallax_theme_registry_alter(&$theme_registry) {

	// Defined path to the current module.
	  $module_path = drupal_get_path('module', 'pt_parallax');
	// Find all .tpl.php files in this module's folder recursively.
	  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
	// Iterate through all found template file objects.
	    foreach ($template_file_objects as $key => $template_file_object) {
	// If the template has not already been overridden by a theme.
	      if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])){
	// Alter the theme path and template elements.
        $theme_registry[$key]['theme path'] = $module_path;
        $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
        $theme_registry[$key]['type'] = 'module';
      }
    }
}

/*
 * Parallax structure preparation
 */
function pt_parallax_get_slide($data,$slide) {
	$output = '';
	$content = '';
	// If type of parallax slide is divider - set content as divider type html structure
	$slide_array = array("slide"=>$slide);
	$output = theme($data . "slide", $slide_array);
	return $output; 
}


